AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - tylerstarlink::tylerstarlink
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  TylerstarlinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tylerstarlink.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/tylerstarlink-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  TylerstarlinkApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: TylerstarlinkApi
